/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsNumberRouteImport } from './routes/levels.$number'
import { Route as LevelsNumberResultRouteImport } from './routes/levels.$number.result'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsNumberRoute = LevelsNumberRouteImport.update({
  id: '/levels/$number',
  path: '/levels/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsNumberResultRoute = LevelsNumberResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => LevelsNumberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/levels/$number' | '/levels/$number/result'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/levels/$number' | '/levels/$number/result'
  id: '__root__' | '/' | '/levels/$number' | '/levels/$number/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LevelsNumberRoute: typeof LevelsNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$number': {
      id: '/levels/$number'
      path: '/levels/$number'
      fullPath: '/levels/$number'
      preLoaderRoute: typeof LevelsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$number/result': {
      id: '/levels/$number/result'
      path: '/result'
      fullPath: '/levels/$number/result'
      preLoaderRoute: typeof LevelsNumberResultRouteImport
      parentRoute: typeof LevelsNumberRoute
    }
  }
}

interface LevelsNumberRouteChildren {
  LevelsNumberResultRoute: typeof LevelsNumberResultRoute
}

const LevelsNumberRouteChildren: LevelsNumberRouteChildren = {
  LevelsNumberResultRoute: LevelsNumberResultRoute,
}

const LevelsNumberRouteWithChildren = LevelsNumberRoute._addFileChildren(
  LevelsNumberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LevelsNumberRoute: LevelsNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
