/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LevelsNumberRouteImport } from './routes/levels.$number'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as LevelsNumberResultRouteImport } from './routes/levels.$number.result'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsNumberRoute = LevelsNumberRouteImport.update({
  id: '/levels/$number',
  path: '/levels/$number',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LevelsNumberResultRoute = LevelsNumberResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => LevelsNumberRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/progress': typeof ProgressRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/progress': typeof ProgressRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/progress': typeof ProgressRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/levels/$number': typeof LevelsNumberRouteWithChildren
  '/levels/$number/result': typeof LevelsNumberResultRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/progress'
    | '/dashboard'
    | '/levels/$number'
    | '/levels/$number/result'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/progress'
    | '/dashboard'
    | '/levels/$number'
    | '/levels/$number/result'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/progress'
    | '/_authenticated/dashboard'
    | '/levels/$number'
    | '/levels/$number/result'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ProgressRoute: typeof ProgressRoute
  LevelsNumberRoute: typeof LevelsNumberRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$number': {
      id: '/levels/$number'
      path: '/levels/$number'
      fullPath: '/levels/$number'
      preLoaderRoute: typeof LevelsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/levels/$number/result': {
      id: '/levels/$number/result'
      path: '/result'
      fullPath: '/levels/$number/result'
      preLoaderRoute: typeof LevelsNumberResultRouteImport
      parentRoute: typeof LevelsNumberRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LevelsNumberRouteChildren {
  LevelsNumberResultRoute: typeof LevelsNumberResultRoute
}

const LevelsNumberRouteChildren: LevelsNumberRouteChildren = {
  LevelsNumberResultRoute: LevelsNumberResultRoute,
}

const LevelsNumberRouteWithChildren = LevelsNumberRoute._addFileChildren(
  LevelsNumberRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ProgressRoute: ProgressRoute,
  LevelsNumberRoute: LevelsNumberRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
